esphome:
  name: bedroomac
  platform: ESP8266
  board: d1_mini

substitutions:
  name: Bedroom AC

# Enable logging
logger:
 baud_rate: 0
 
# Enable Home Assistant API
api:

ota:
  password: !secret bedroomac_ota_pw

# Enable Web server.
web_server:
  port: 80

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroomac Fallback Hotspot"
    password: !secret bedroomac_ota_hotspot_pw

captive_portal:

sensor:
- platform: uptime
  name: ${name} Uptime

  # WiFi Signal sensor.
- platform: wifi_signal
  name: ${name} WiFi Signal
  update_interval: 60s


climate:
  - platform: mitsubishi_heatpump
    name: "Bedroom AC"
    hardware_uart: UART0
    #baud_rate: 9600
    supports:
      mode: [COOL, DRY, FAN_ONLY]
      fan_mode: [AUTO, LOW, MEDIUM, HIGH]
      swing_mode: ["OFF", "VERTICAL"]
    visual:
      min_temperature: 20
      max_temperature: 40
      temperature_step: 1.0
    
  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID
