esphome:
  name: weather-station
  platform: ESP32
  board: esp32dev

substitutions:
  name: weather-station

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Web server.
web_server:
  port: 80

ota:
  password: !secret weather-station_ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather-Station Fallback Hotspot"
    password: !secret weather-station_ota_hotspot_pw

i2c:
  #sda: 22
  #scl: 21
  #scan: true
  id: bus_a

sensor:
- platform: bme280
  i2c_id: bus_a
  temperature:
   name: "BME280 Temperature"
   oversampling: 16x
  pressure:
   name: "BME280 Pressure"
  humidity:
   name: "BME280 Humidity"
  address: 0x76
  update_interval: 30s

- platform: bh1750
  i2c_id: bus_a
  name: Lux
  address: 0x23
  update_interval: 25s
  
- platform: adc
  pin: A0
  name: "Solar Weather Station Battery"
  update_interval: 30s
  accuracy_decimals: 4
  filters:
   - multiply: 5.1923
   
     # WiFi Signal sensor.
- platform: wifi_signal
  name: ${name} WiFi Signal
  update_interval: 60s

deep_sleep:
  run_duration: 60s
  sleep_duration: 4min

status_led:
  pin: GPIO2
  
  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID
